server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5454/notification
    username: blackscorpion
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
  instance:
    hostname: localhost
    prefer-ip-address: true
management:
  tracing:
    sampling:
      probability: 1.0

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key